name: "mythrnr-wmf-rs"

services:
  dev:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile"
    image: "mythrnr-wmf-rs-dev:latest"
    init: true
    # `tty` + `stdin_open` make `docker compose run --rm dev` behave as
    # a normal interactive shell.
    tty: true
    stdin_open: true
    environment:
      CARGO_BUILD_TARGET_DIR: "/target"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - type: "volume"
        source: "cargo_registry"
        target: "/usr/local/cargo/registry"
        read_only: false
      - type: "volume"
        source: "cargo_git"
        target: "/usr/local/cargo/git"
        read_only: false
      - type: "volume"
        source: "target"
        target: "/target"
        read_only: false
      - type: "bind"
        source: ".."
        target: "/work"
        read_only: false
    working_dir: "/work"

volumes:
  cargo_registry:
  cargo_git:
  target:
