use crate::imports::*;

/// The TernaryRasterOperation Enumeration specifies ternary raster operation
/// codes, which define how to combine the bits in a source bitmap with the bits
/// in a destination bitmap.
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    strum::FromRepr,
    strum::EnumIter,
)]
#[repr(u32)]
pub enum TernaryRasterOperation {
    // cSpell:disable
    /// Common = 0
    BLACKNESS = 0x00000042,
    /// Common = DPSoon
    DPSOON = 0x00010289,
    /// Common = DPSona
    DPSONA = 0x00020C89,
    /// Common = PSon
    PSON = 0x000300AA,
    /// Common = SDPona
    SDPONA = 0x00040C88,
    /// Common = DPon
    DPON = 0x000500A9,
    /// Common = PDSxnon
    PDSXNON = 0x00060865,
    /// Common = PDSaon
    PDSAON = 0x000702C5,
    /// Common = SDPnaa
    SDPNAA = 0x00080F08,
    /// Common = PDSxon
    PDSXON = 0x00090245,
    /// Common = DPna
    DPNA = 0x000A0329,
    /// Common = PSDnaon
    PSDNAON = 0x000B0B2A,
    /// Common = SPna
    SPNA = 0x000C0324,
    /// Common = PDSnaon
    PDSNAON = 0x000D0B25,
    /// Common = PDSonon
    PDSONON = 0x000E08A5,
    /// Common = Pn
    PN = 0x000F0001,
    /// Common = PDSona
    PDSONA = 0x00100C85,
    /// Common = DSon
    NOTSRCERASE = 0x001100A6,
    /// Common = SDPxnon
    SDPXNON = 0x00120868,
    /// Common = SDPaon
    SDPAON = 0x001302C8,
    /// Common = DPSxnon
    DPSXNON = 0x00140869,
    /// Common = DPSaon
    DPSAON = 0x001502C9,
    /// Common = PSDPSanaxx
    PSDPSANAXX = 0x00165CCA,
    /// Common = SSPxDSxaxn
    SSPXDSXAXN = 0x00171D54,
    /// Common = SPxPDxa
    SPXPDXA = 0x00180D59,
    /// Common = SDPSanaxn
    SDPSANAXN = 0x00191CC8,
    /// Common = PDSPaox
    PDSPAOX = 0x001A06C5,
    /// Common = SDPSxaxn
    SDPSXAXN = 0x001B0768,
    /// Common = PSDPaox
    PSDPAOX = 0x001C06CA,
    /// Common = DSPDxaxn
    DSPDXAXN = 0x001D0766,
    /// Common = PDSox
    PDSOX = 0x001E01A5,
    /// Common = PDSoan
    PDSOAN = 0x001F0385,
    /// Common = DPSnaa
    DPSNAA = 0x00200F09,
    /// Common = SDPxon
    SDPXON = 0x00210248,
    /// Common = DSna
    DSNA = 0x00220326,
    /// Common = SPDnaon
    SPDNAON = 0x00230B24,
    /// Common = SPxDSxa
    SPXDSXA = 0x00240D55,
    /// Common = PDSPanaxn
    PDSPANAXN = 0x00251CC5,
    /// Common = SDPSaox
    SDPSAOX = 0x002606C8,
    /// Common = SDPSxnox
    SDPSXNOX = 0x00271868,
    /// Common = DPSxa
    DPSXA = 0x00280369,
    /// Common = PSDPSaoxxn
    PSDPSAOXXN = 0x002916CA,
    /// Common = DPSana
    DPSANA = 0x002A0CC9,
    /// Common = SSPxPDxaxn
    SSPXPDXAXN = 0x002B1D58,
    /// Common = SPDSoax
    SPDSOAX = 0x002C0784,
    /// Common = PSDnox
    PSDNOX = 0x002D060A,
    /// Common = PSDPxox
    PSDPXOX = 0x002E064A,
    /// Common = PSDnoan
    PSDNOAN = 0x002F0E2A,
    /// Common = PSna
    PSNA = 0x0030032A,
    /// Common = SDPnaon
    SDPNAON = 0x00310B28,
    /// Common = SDPSoox
    SDPSOOX = 0x00320688,
    /// Common = Sn
    NOTSRCCOPY = 0x00330008,
    /// Common = SPDSaox
    SPDSAOX = 0x003406C4,
    /// Common = SPDSxnox
    SPDSXNOX = 0x00351864,
    /// Common = SDPox
    SDPOX = 0x003601A8,
    /// Common = SDPoan
    SDPOAN = 0x00370388,
    /// Common = PSDPoax
    PSDPOAX = 0x0038078A,
    /// Common = SPDnox
    SPDNOX = 0x0390604,
    /// Common = SPDSxox
    SPDSXOX = 0x003A0644,
    /// Common = SPDnoan
    SPDNOAN = 0x003B0E24,
    /// Common = PSx
    PSX = 0x003C004A,
    /// Common = SPDSonox
    SPDSONOX = 0x003D18A4,
    /// Common = SPDSnaox
    SPDSNAOX = 0x003E1B24,
    /// Common = PSan
    PSAN = 0x003F00EA,
    /// Common = PSDnaa
    PSDNAA = 0x00400F0A,
    /// Common = DPSxon
    DPSXON = 0x00410249,
    /// Common = SDxPDxa
    SDXPDXA = 0x00420D5D,
    /// Common = SPDSanaxn
    SPDSANAXN = 0x00431CC4,
    /// Common = SDna
    SRCERASE = 0x00440328,
    /// Common = DPSnaon
    DPSNAON = 0x00450B29,
    /// Common = DSPDaox
    DSPDAOX = 0x004606C6,
    /// Common = PSDPxaxn
    PSDPXAXN = 0x0047076A,
    /// Common = SDPxa
    SDPXA = 0x00480368,
    /// Common = PDSPDaoxxn
    PDSPDAOXXN = 0x004916C5,
    /// Common = DPSDoax
    DPSDOAX = 0x004A0789,
    /// Common = PDSnox
    PDSNOX = 0x004B0605,
    /// Common = SDPana
    SDPANA = 0x004C0CC8,
    /// Common = SSPxDSxoxn
    SSPXDSXOXN = 0x004D1954,
    /// Common = PDSPxox
    PDSPXOX = 0x004E0645,
    /// Common = PDSnoan
    PDSNOAN = 0x004F0E25,
    /// Common = PDna
    PDNA = 0x00500325,
    /// Common = DSPnaon
    DSPNAON = 0x00510B26,
    /// Common = DPSDaox
    DPSDAOX = 0x005206C9,
    /// Common = SPDSxaxn
    SPDSXAXN = 0x00530764,
    /// Common = DPSonon
    DPSONON = 0x005408A9,
    /// Common = Dn
    DSTINVERT = 0x00550009,
    /// Common = DPSox
    DPSOX = 0x005601A9,
    /// Common = DPSoan
    DPSOAN = 0x000570389,
    /// Common = PDSPoax
    PDSPOAX = 0x00580785,
    /// Common = DPSnox
    DPSNOX = 0x00590609,
    /// Common = DPx
    PATINVERT = 0x005A0049,
    /// Common = DPSDonox
    DPSDONOX = 0x005B18A9,
    /// Common = DPSDxox
    DPSDXOX = 0x005C0649,
    /// Common = DPSnoan
    DPSNOAN = 0x005D0E29,
    /// Common = DPSDnaox
    DPSDNAOX = 0x005E1B29,
    /// Common = DPan
    DPAN = 0x005F00E9,
    /// Common = PDSxa
    PDSXA = 0x00600365,
    /// Common = DSPDSaoxxn
    DSPDSAOXXN = 0x006116C6,
    /// Common = DSPDoax
    DSPDOAX = 0x00620786,
    /// Common = SDPnox
    SDPNOX = 0x00630608,
    /// Common = SDPSoax
    SDPSOAX = 0x00640788,
    /// Common = DSPnox
    DSPNOX = 0x00650606,
    /// Common = DSx
    SRCINVERT = 0x00660046,
    /// Common = SDPSonox
    SDPSONOX = 0x006718A8,
    /// Common = DSPDSonoxxn
    DSPDSONOXXN = 0x006858A6,
    /// Common = PDSxxn
    PDSXXN = 0x00690145,
    /// Common = DPSax
    DPSAX = 0x006A01E9,
    /// Common = PSDPSoaxxn
    PSDPSOAXXN = 0x006B178A,
    /// Common = SDPax
    SDPAX = 0x006C01E8,
    /// Common = PDSPDoaxxn
    PDSPDOAXXN = 0x006D1785,
    /// Common = SDPSnoax
    SDPSNOAX = 0x006E1E28,
    /// Common = PDXnan
    PDXNAN = 0x006F0C65,
    /// Common = PDSana
    PDSANA = 0x00700CC5,
    /// Common = SSDxPDxaxn
    SSDXPDXAXN = 0x00711D5C,
    /// Common = SDPSxox
    SDPSXOX = 0x00720648,
    /// Common = SDPnoan
    SDPNOAN = 0x00730E28,
    /// Common = DSPDxox
    DSPDXOX = 0x00740646,
    /// Common = DSPnoan
    DSPNOAN = 0x00750E26,
    /// Common = SDPSnaox
    SDPSNAOX = 0x00761B28,
    /// Common = DSan
    DSAN = 0x007700E6,
    /// Common = PDSax
    PDSAX = 0x007801E5,
    /// Common = DSPDSoaxxn
    DSPDSOAXXN = 0x00791786,
    /// Common = DPSDnoax
    DPSDNOAX = 0x007A1E29,
    /// Common = SDPxnan
    SDPXNAN = 0x007B0C68,
    /// Common = SPDSnoax
    SPDSNOAX = 0x007C1E24,
    /// Common = DPSxnan
    DPSXNAN = 0x007D0C69,
    /// Common = SPxDSxo
    SPXDSXO = 0x007E0955,
    /// Common = DPSaan
    DPSAAN = 0x007F03C9,
    /// Common = DPSaa
    DPSAA = 0x008003E9,
    /// Common = SPxDSxon
    SPXDSXON = 0x00810975,
    /// Common = DPSxna
    DPSXNA = 0x00820C49,
    /// Common = SPDSnoaxn
    SPDSNOAXN = 0x00831E04,
    /// Common = SDPxna
    SDPXNA = 0x00840C48,
    /// Common = PDSPnoaxn
    PDSPNOAXN = 0x00851E05,
    /// Common = DSPDSoaxx
    DSPDSOAXX = 0x008617A6,
    /// Common = PDSaxn
    PDSAXN = 0x008701C5,
    /// Common = DSa
    SRCAND = 0x008800C6,
    /// Common = SDPSnaoxn
    SDPSNAOXN = 0x00891B08,
    /// Common = DSPnoa
    DSPNOA = 0x008A0E06,
    /// Common = DSPDxoxn
    DSPDXOXN = 0x008B0666,
    /// Common = SDPnoa
    SDPNOA = 0x008C0E08,
    /// Common = SDPSxoxn
    SDPSXOXN = 0x008D0668,
    /// Common = SSDxPDxax
    SSDXPDXAX = 0x008E1D7C,
    /// Common = PDSanan
    PDSANAN = 0x008F0CE5,
    /// Common = PDSxna
    PDSXNA = 0x00900C45,
    /// Common = SDPSnoaxn
    SDPSNOAXN = 0x00911E08,
    /// Common = DPSDPoaxx
    DPSDPOAXX = 0x009217A9,
    /// Common = SPDaxn
    SPDAXN = 0x009301C4,
    /// Common = PSDPSoaxx
    PSDPSOAXX = 0x009417AA,
    /// Common = DPSaxn
    DPSAXN = 0x009501C9,
    /// Common = DPSxx
    DPSXX = 0x00960169,
    /// Common = PSDPSonoxx
    PSDPSONOXX = 0x0097588A,
    /// Common = SDPSonoxn
    SDPSONOXN = 0x00981888,
    /// Common = DSxn
    DSXN = 0x00990066,
    /// Common = DPSnax
    DPSNAX = 0x009A0709,
    /// Common = SDPSoaxn
    SDPSOAXN = 0x009B07A8,
    /// Common = SPDnax
    SPDNAX = 0x009C0704,
    /// Common = DSPDoaxn
    DSPDOAXN = 0x009D07A6,
    /// Common = DSPDSaoxx
    DSPDSAOXX = 0x009E16E6,
    /// Common = PDSxan
    PDSXAN = 0x009F0345,
    /// Common = DPa
    DPA = 0x00A000C9,
    /// Common = PDSPnaoxn
    PDSPNAOXN = 0x00A11B05,
    /// Common = DPSnoa
    DPSNOA = 0x00A20E09,
    /// Common = DPSDxoxn
    DPSDXOXN = 0x00A30669,
    /// Common = PDSPonoxn
    PDSPONOXN = 0x00A41885,
    /// Common = PDxn
    PDXN = 0x00A50065,
    /// Common = DSPnax
    DSPNAX = 0x00A60706,
    /// Common = PDSPoaxn
    PDSPOAXN = 0x00A707A5,
    /// Common = DPSoa
    DPSOA = 0x00A803A9,
    /// Common = DPSoxn
    DPSOXN = 0x00A90189,
    /// Common = D
    D = 0x00AA0029,
    /// Common = DPSono
    DPSONO = 0x00AB0889,
    /// Common = SPDSxax
    SPDSXAX = 0x00AC0744,
    /// Common = DPSDaoxn
    DPSDAOXN = 0x00AD06E9,
    /// Common = DSPnao
    DSPNAO = 0x00AE0B06,
    /// Common = DPno
    DPNO = 0x00AF0229,
    /// Common = PDSnoa
    PDSNOA = 0x00B00E05,
    /// Common = PDSPxoxn
    PDSPXOXN = 0x00B10665,
    /// Common = SSPxDSxox
    SSPXDSXOX = 0x00B21974,
    /// Common = SDPanan
    SDPANAN = 0x00B30CE8,
    /// Common = PSDnax
    PSDNAX = 0x00B4070A,
    /// Common = DPSDoaxn
    DPSDOAXN = 0x00B507A9,
    /// Common = DPSDPaoxx
    DPSDPAOXX = 0x00B616E9,
    /// Common = SDPxan
    SDPXAN = 0x00B70348,
    /// Common = PSDPxax
    PSDPXAX = 0x00B8074A,
    /// Common = DSPDaoxn
    DSPDAOXN = 0x00B906E6,
    /// Common = DPSnao
    DPSNAO = 0x00BA0B09,
    /// Common = DSno
    MERGEPAINT = 0x00BB0226,
    /// Common = SPDSanax
    SPDSANAX = 0x00BC1CE4,
    /// Common = SDxPDxan
    SDXPDXAN = 0x00BD0D7D,
    /// Common = DPSxo
    DPSXO = 0x00BE0269,
    /// Common = DPSano
    DPSANO = 0x00BF08C9,
    /// Common = PSa
    MERGECOPY = 0x00C000CA,
    /// Common = SPDSnaoxn
    SPDSNAOXN = 0x00C11B04,
    /// Common = SPDSonoxn
    SPDSONOXN = 0x00C21884,
    /// Common = PSxn
    PSXN = 0x00C3006A,
    /// Common = SPDnoa
    SPDNOA = 0x00C40E04,
    /// Common = SPDSxoxn
    SPDSXOXN = 0x00C50664,
    /// Common = SDPnax
    SDPNAX = 0x00C60708,
    /// Common = PSDPoaxn
    PSDPOAXN = 0x00C707AA,
    /// Common = SDPoa
    SDPOA = 0x00C803A8,
    /// Common = SPDoxn
    SPDOXN = 0x00C90184,
    /// Common = DPSDxax
    DPSDXAX = 0x00CA0749,
    /// Common = SPDSaoxn
    SPDSAOXN = 0x00CB06E4,
    /// Common = S
    SRCCOPY = 0x00CC0020,
    /// Common = SDPono
    SDPONO = 0x00CD0888,
    /// Common = SDPnao
    SDPNAO = 0x00CE0B08,
    /// Common = SPno
    SPNO = 0x00CF0224,
    /// Common = PSDnoa
    PSDNOA = 0x00D00E0A,
    /// Common = PSDPxoxn
    PSDPXOXN = 0x00D1066A,
    /// Common = PDSnax
    PDSNAX = 0x00D20705,
    /// Common = SPDSoaxn
    SPDSOAXN = 0x00D307A4,
    /// Common = SSPxPDxax
    SSPXPDXAX = 0x00D41D78,
    /// Common = DPSanan
    DPSANAN = 0x00D50CE9,
    /// Common = PSDPSaoxx
    PSDPSAOXX = 0x00D616EA,
    /// Common = DPSxan
    DPSXAN = 0x00D70349,
    /// Common = PDSPxax
    PDSPXAX = 0x00D80745,
    /// Common = SDPSaoxn
    SDPSAOXN = 0x00D906E8,
    /// Common = DPSDanax
    DPSDANAX = 0x00DA1CE9,
    /// Common = SPxDSxan
    SPXDSXAN = 0x00DB0D75,
    /// Common = SPDnao
    SPDNAO = 0x00DC0B04,
    /// Common = SDno
    SDNO = 0x00DD0228,
    /// Common = SDPxo
    SDPXO = 0x00DE0268,
    /// Common = SDPano
    SDPANO = 0x00DF08C8,
    /// Common = PDSoa
    PDSOA = 0x00E003A5,
    /// Common = PDSoxn
    PDSOXN = 0x00E10185,
    /// Common = DSPDxax
    DSPDXAX = 0x00E20746,
    /// Common = PSDPaoxn
    PSDPAOXN = 0x00E306EA,
    /// Common = SDPSxax
    SDPSXAX = 0x00E40748,
    /// Common = PDSPaoxn
    PDSPAOXN = 0x00E506E5,
    /// Common = SDPSanax
    SDPSANAX = 0x00E61CE8,
    /// Common = SPxPDxan
    SPXPDXAN = 0x00E70D79,
    /// Common = SSPxDSxax
    SSPXDSXAX = 0x00E81D74,
    /// Common = DSPDSanaxxn
    DSPDSANAXXN = 0x00E95CE6,
    /// Common = DPSao
    DPSAO = 0x00EA02E9,
    /// Common = DPSxno
    DPSXNO = 0x00EB0849,
    /// Common = SDPao
    SDPAO = 0x00EC02E8,
    /// Common = SDPxno
    SDPXNO = 0x00ED0848,
    /// Common = DSo
    SRCPAINT = 0x00EE0086,
    /// Common = SDPnoo
    SDPNOO = 0x00EF0A08,
    /// Common = P
    PATCOPY = 0x00F00021,
    /// Common = PDSono
    PDSONO = 0x00F10885,
    /// Common = PDSnao
    PDSNAO = 0x00F20B05,
    /// Common = PSno
    PSNO = 0x00F3022A,
    /// Common = PSDnao
    PSDNAO = 0x00F40B0A,
    /// Common = PDno
    PDNO = 0x00F50225,
    /// Common = PDSxo
    PDSXO = 0x00F60265,
    /// Common = PDSano
    PDSANO = 0x00F708C5,
    /// Common = PDSao
    PDSAO = 0x00F802E5,
    /// Common = PDSxno
    PDSXNO = 0x00F90845,
    /// Common = DPo
    DPO = 0x00FA0089,
    /// Common = DPSnoo
    PATPAINT = 0x00FB0A09,
    /// Common = PSo
    PSO = 0x00FC008A,
    /// Common = PSDnoo
    PSDNOO = 0x00FD0A0A,
    /// Common = DPSoo
    DPSOO = 0x00FE02A9,
    /// Common = 1
    WHITENESS = 0x00FF0062,
    // cSpell:enable
}

crate::parser::constants::impl_parser!(TernaryRasterOperation, u32);

impl TernaryRasterOperation {
    // const OPERAND_DESTINATION_BITMAP: &'static str = "D";
    const OPERAND_SELECTED_BRUSH: &'static str = "P";
    const OPERAND_SOURCE_BITMAP: &'static str = "S";

    pub fn use_selected_brush(&self) -> bool {
        self.as_reverse_polish_notation().contains(Self::OPERAND_SELECTED_BRUSH)
    }

    pub fn use_source(&self) -> bool {
        self.as_reverse_polish_notation().contains(Self::OPERAND_SOURCE_BITMAP)
    }

    fn as_reverse_polish_notation(self) -> String {
        match self {
            // cSpell:disable
            Self::BLACKNESS => "0",
            Self::DPSOON => "DPSoon",
            Self::DPSONA => "DPSona",
            Self::PSON => "PSon",
            Self::SDPONA => "SDPona",
            Self::DPON => "DPon",
            Self::PDSXNON => "PDSxnon",
            Self::PDSAON => "PDSaon",
            Self::SDPNAA => "SDPnaa",
            Self::PDSXON => "PDSxon",
            Self::DPNA => "DPna",
            Self::PSDNAON => "PSDnaon",
            Self::SPNA => "SPna",
            Self::PDSNAON => "PDSnaon",
            Self::PDSONON => "PDSonon",
            Self::PN => "Pn",
            Self::PDSONA => "PDSona",
            Self::NOTSRCERASE => "DSon",
            Self::SDPXNON => "SDPxnon",
            Self::SDPAON => "SDPaon",
            Self::DPSXNON => "DPSxnon",
            Self::DPSAON => "DPSaon",
            Self::PSDPSANAXX => "PSDPSanaxx",
            Self::SSPXDSXAXN => "SSPxDSxaxn",
            Self::SPXPDXA => "SPxPDxa",
            Self::SDPSANAXN => "SDPSanaxn",
            Self::PDSPAOX => "PDSPaox",
            Self::SDPSXAXN => "SDPSxaxn",
            Self::PSDPAOX => "PSDPaox",
            Self::DSPDXAXN => "DSPDxaxn",
            Self::PDSOX => "PDSox",
            Self::PDSOAN => "PDSoan",
            Self::DPSNAA => "DPSnaa",
            Self::SDPXON => "SDPxon",
            Self::DSNA => "DSna",
            Self::SPDNAON => "SPDnaon",
            Self::SPXDSXA => "SPxDSxa",
            Self::PDSPANAXN => "PDSPanaxn",
            Self::SDPSAOX => "SDPSaox",
            Self::SDPSXNOX => "SDPSxnox",
            Self::DPSXA => "DPSxa",
            Self::PSDPSAOXXN => "PSDPSaoxxn",
            Self::DPSANA => "DPSana",
            Self::SSPXPDXAXN => "SSPxPDxaxn",
            Self::SPDSOAX => "SPDSoax",
            Self::PSDNOX => "PSDnox",
            Self::PSDPXOX => "PSDPxox",
            Self::PSDNOAN => "PSDnoan",
            Self::PSNA => "PSna",
            Self::SDPNAON => "SDPnaon",
            Self::SDPSOOX => "SDPSoox",
            Self::NOTSRCCOPY => "Sn",
            Self::SPDSAOX => "SPDSaox",
            Self::SPDSXNOX => "SPDSxnox",
            Self::SDPOX => "SDPox",
            Self::SDPOAN => "SDPoan",
            Self::PSDPOAX => "PSDPoax",
            Self::SPDNOX => "SPDnox",
            Self::SPDSXOX => "SPDSxox",
            Self::SPDNOAN => "SPDnoan",
            Self::PSX => "PSx",
            Self::SPDSONOX => "SPDSonox",
            Self::SPDSNAOX => "SPDSnaox",
            Self::PSAN => "PSan",
            Self::PSDNAA => "PSDnaa",
            Self::DPSXON => "DPSxon",
            Self::SDXPDXA => "SDxPDxa",
            Self::SPDSANAXN => "SPDSanaxn",
            Self::SRCERASE => "SDna",
            Self::DPSNAON => "DPSnaon",
            Self::DSPDAOX => "DSPDaox",
            Self::PSDPXAXN => "PSDPxaxn",
            Self::SDPXA => "SDPxa",
            Self::PDSPDAOXXN => "PDSPDaoxxn",
            Self::DPSDOAX => "DPSDoax",
            Self::PDSNOX => "PDSnox",
            Self::SDPANA => "SDPana",
            Self::SSPXDSXOXN => "SSPxDSxoxn",
            Self::PDSPXOX => "PDSPxox",
            Self::PDSNOAN => "PDSnoan",
            Self::PDNA => "PDna",
            Self::DSPNAON => "DSPnaon",
            Self::DPSDAOX => "DPSDaox",
            Self::SPDSXAXN => "SPDSxaxn",
            Self::DPSONON => "DPSonon",
            Self::DSTINVERT => "Dn",
            Self::DPSOX => "DPSox",
            Self::DPSOAN => "DPSoan",
            Self::PDSPOAX => "PDSPoax",
            Self::DPSNOX => "DPSnox",
            Self::PATINVERT => "DPx",
            Self::DPSDONOX => "DPSDonox",
            Self::DPSDXOX => "DPSDxox",
            Self::DPSNOAN => "DPSnoan",
            Self::DPSDNAOX => "DPSDnaox",
            Self::DPAN => "DPan",
            Self::PDSXA => "PDSxa",
            Self::DSPDSAOXXN => "DSPDSaoxxn",
            Self::DSPDOAX => "DSPDoax",
            Self::SDPNOX => "SDPnox",
            Self::SDPSOAX => "SDPSoax",
            Self::DSPNOX => "DSPnox",
            Self::SRCINVERT => "DSx",
            Self::SDPSONOX => "SDPSonox",
            Self::DSPDSONOXXN => "DSPDSonoxxn",
            Self::PDSXXN => "PDSxxn",
            Self::DPSAX => "DPSax",
            Self::PSDPSOAXXN => "PSDPSoaxxn",
            Self::SDPAX => "SDPax",
            Self::PDSPDOAXXN => "PDSPDoaxxn",
            Self::SDPSNOAX => "SDPSnoax",
            Self::PDXNAN => "PDXnan",
            Self::PDSANA => "PDSana",
            Self::SSDXPDXAXN => "SSDxPDxaxn",
            Self::SDPSXOX => "SDPSxox",
            Self::SDPNOAN => "SDPnoan",
            Self::DSPDXOX => "DSPDxox",
            Self::DSPNOAN => "DSPnoan",
            Self::SDPSNAOX => "SDPSnaox",
            Self::DSAN => "DSan",
            Self::PDSAX => "PDSax",
            Self::DSPDSOAXXN => "DSPDSoaxxn",
            Self::DPSDNOAX => "DPSDnoax",
            Self::SDPXNAN => "SDPxnan",
            Self::SPDSNOAX => "SPDSnoax",
            Self::DPSXNAN => "DPSxnan",
            Self::SPXDSXO => "SPxDSxo",
            Self::DPSAAN => "DPSaan",
            Self::DPSAA => "DPSaa",
            Self::SPXDSXON => "SPxDSxon",
            Self::DPSXNA => "DPSxna",
            Self::SPDSNOAXN => "SPDSnoaxn",
            Self::SDPXNA => "SDPxna",
            Self::PDSPNOAXN => "PDSPnoaxn",
            Self::DSPDSOAXX => "DSPDSoaxx",
            Self::PDSAXN => "PDSaxn",
            Self::SRCAND => "DSa",
            Self::SDPSNAOXN => "SDPSnaoxn",
            Self::DSPNOA => "DSPnoa",
            Self::DSPDXOXN => "DSPDxoxn",
            Self::SDPNOA => "SDPnoa",
            Self::SDPSXOXN => "SDPSxoxn",
            Self::SSDXPDXAX => "SSDxPDxax",
            Self::PDSANAN => "PDSanan",
            Self::PDSXNA => "PDSxna",
            Self::SDPSNOAXN => "SDPSnoaxn",
            Self::DPSDPOAXX => "DPSDPoaxx",
            Self::SPDAXN => "SPDaxn",
            Self::PSDPSOAXX => "PSDPSoaxx",
            Self::DPSAXN => "DPSaxn",
            Self::DPSXX => "DPSxx",
            Self::PSDPSONOXX => "PSDPSonoxx",
            Self::SDPSONOXN => "SDPSonoxn",
            Self::DSXN => "DSxn",
            Self::DPSNAX => "DPSnax",
            Self::SDPSOAXN => "SDPSoaxn",
            Self::SPDNAX => "SPDnax",
            Self::DSPDOAXN => "DSPDoaxn",
            Self::DSPDSAOXX => "DSPDSaoxx",
            Self::PDSXAN => "PDSxan",
            Self::DPA => "DPa",
            Self::PDSPNAOXN => "PDSPnaoxn",
            Self::DPSNOA => "DPSnoa",
            Self::DPSDXOXN => "DPSDxoxn",
            Self::PDSPONOXN => "PDSPonoxn",
            Self::PDXN => "PDxn",
            Self::DSPNAX => "DSPnax",
            Self::PDSPOAXN => "PDSPoaxn",
            Self::DPSOA => "DPSoa",
            Self::DPSOXN => "DPSoxn",
            Self::D => "D",
            Self::DPSONO => "DPSono",
            Self::SPDSXAX => "SPDSxax",
            Self::DPSDAOXN => "DPSDaoxn",
            Self::DSPNAO => "DSPnao",
            Self::DPNO => "DPno",
            Self::PDSNOA => "PDSnoa",
            Self::PDSPXOXN => "PDSPxoxn",
            Self::SSPXDSXOX => "SSPxDSxox",
            Self::SDPANAN => "SDPanan",
            Self::PSDNAX => "PSDnax",
            Self::DPSDOAXN => "DPSDoaxn",
            Self::DPSDPAOXX => "DPSDPaoxx",
            Self::SDPXAN => "SDPxan",
            Self::PSDPXAX => "PSDPxax",
            Self::DSPDAOXN => "DSPDaoxn",
            Self::DPSNAO => "DPSnao",
            Self::MERGEPAINT => "DSno",
            Self::SPDSANAX => "SPDSanax",
            Self::SDXPDXAN => "SDxPDxan",
            Self::DPSXO => "DPSxo",
            Self::DPSANO => "DPSano",
            Self::MERGECOPY => "PSa",
            Self::SPDSNAOXN => "SPDSnaoxn",
            Self::SPDSONOXN => "SPDSonoxn",
            Self::PSXN => "PSxn",
            Self::SPDNOA => "SPDnoa",
            Self::SPDSXOXN => "SPDSxoxn",
            Self::SDPNAX => "SDPnax",
            Self::PSDPOAXN => "PSDPoaxn",
            Self::SDPOA => "SDPoa",
            Self::SPDOXN => "SPDoxn",
            Self::DPSDXAX => "DPSDxax",
            Self::SPDSAOXN => "SPDSaoxn",
            Self::SRCCOPY => "S",
            Self::SDPONO => "SDPono",
            Self::SDPNAO => "SDPnao",
            Self::SPNO => "SPno",
            Self::PSDNOA => "PSDnoa",
            Self::PSDPXOXN => "PSDPxoxn",
            Self::PDSNAX => "PDSnax",
            Self::SPDSOAXN => "SPDSoaxn",
            Self::SSPXPDXAX => "SSPxPDxax",
            Self::DPSANAN => "DPSanan",
            Self::PSDPSAOXX => "PSDPSaoxx",
            Self::DPSXAN => "DPSxan",
            Self::PDSPXAX => "PDSPxax",
            Self::SDPSAOXN => "SDPSaoxn",
            Self::DPSDANAX => "DPSDanax",
            Self::SPXDSXAN => "SPxDSxan",
            Self::SPDNAO => "SPDnao",
            Self::SDNO => "SDno",
            Self::SDPXO => "SDPxo",
            Self::SDPANO => "SDPano",
            Self::PDSOA => "PDSoa",
            Self::PDSOXN => "PDSoxn",
            Self::DSPDXAX => "DSPDxax",
            Self::PSDPAOXN => "PSDPaoxn",
            Self::SDPSXAX => "SDPSxax",
            Self::PDSPAOXN => "PDSPaoxn",
            Self::SDPSANAX => "SDPSanax",
            Self::SPXPDXAN => "SPxPDxan",
            Self::SSPXDSXAX => "SSPxDSxax",
            Self::DSPDSANAXXN => "DSPDSanaxxn",
            Self::DPSAO => "DPSao",
            Self::DPSXNO => "DPSxno",
            Self::SDPAO => "SDPao",
            Self::SDPXNO => "SDPxno",
            Self::SRCPAINT => "DSo",
            Self::SDPNOO => "SDPnoo",
            Self::PATCOPY => "P",
            Self::PDSONO => "PDSono",
            Self::PDSNAO => "PDSnao",
            Self::PSNO => "PSno",
            Self::PSDNAO => "PSDnao",
            Self::PDNO => "PDno",
            Self::PDSXO => "PDSxo",
            Self::PDSANO => "PDSano",
            Self::PDSAO => "PDSao",
            Self::PDSXNO => "PDSxno",
            Self::DPO => "DPo",
            Self::PATPAINT => "DPSnoo",
            Self::PSO => "PSo",
            Self::PSDNOO => "PSDnoo",
            Self::DPSOO => "DPSoo",
            Self::WHITENESS => "1",
            // cSpell:enable
        }
        .to_owned()
    }
}
