name: "Check codes"

on:
  pull_request:
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  fmt:
    name: "Run cargo fmt"
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          persist-credentials: false
      - run: "rustup component add --toolchain nightly rustfmt"
      - run: "make fmt"

  clippy:
    name: "Run cargo clippy"
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          persist-credentials: false
      - run: "rustup component add clippy"
      - run: "make lint"

  spell-check:
    name: "Run cSpell"
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          persist-credentials: false
      - run: "make spell-check"

  testing:
    name: "Unit testing"
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          persist-credentials: false
      - run: "make test"
